Repository cmjava2023/vm, pull requests merged in 2023-12, with the labels that each got.

#57 Finishing parsing of primitive datatypes
  src/classloader/opcode_parser.rs
  src/executor/op_code.rs
Labels: kind::feature, priority::high, status::acceptance test

#58 [executor] array support
  src/bin/cmjava.rs
  src/class.rs
  src/class/builtin_classes.rs
  src/class/builtin_classes/array.rs
  src/class/builtin_classes/print_stream.rs
  src/class/builtin_classes/string.rs
  src/class/builtin_classes/system.rs
  src/class/bytecode_classes.rs
  src/classloader/opcode_parser.rs
  src/executor.rs
  src/executor/op_code.rs
  src/heap.rs
Labels: kind::feature, priority::high, status::in progress

#63 Branch offsets by opcodes and wide opcode
  src/classloader/opcode_parser.rs
  src/executor/op_code.rs
Labels: kind::feature, status::acceptance test

#62 [executor] remaining array opcodes
  src/class/builtin_classes/array.rs
  src/executor/op_code.rs
Labels: kind::feature, priority::high, status::acceptance test

#68 [executor] missing opcodes for array testcase
  src/executor/frame_stack.rs
  src/executor/op_code.rs
Labels: kind::feature, priority::normal, status::acceptance test

#70 feat(executor): remaining primitiv opcodes
  src/classloader/opcode_parser.rs
  src/executor/op_code.rs
  tests/data/primitive/double/conversions/Main.class
  tests/data/primitive/double/conversions/Main.java
  tests/data/primitive/double/conversions/Main.javap
  tests/primitive/double.rs
  tests/primitive/float.rs
  tests/primitive/int.rs
  tests/primitive/long.rs
Labels: kind::feature, priority::normal, status::acceptance test

#74 Add class to read input from stdin
  src/class.rs
  src/class/builtin_classes.rs
  src/class/builtin_classes/file_input_stream.rs
  src/class/builtin_classes/input_stream.rs
  src/class/builtin_classes/system.rs
  src/executor.rs
  src/heap.rs
  tests/data/input/Main.class
  tests/data/input/Main.java
  tests/data/input/Main.javap
  tests/input.rs
Labels: kind::feature, priority::normal, status::blocked, status::in progress

#82 parse ordered list of class files
  src/bin/cmjava.rs
Labels: kind::feature, priority::high
